# Generated by Django 3.2.13 on 2022-05-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220504_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.covercolor'),
            preserve_default=False,
        ),
    ]
